parameters:
  - name: ClientName
    type: string
    default: ''
  - name: Environment
    type: string
    default: ''
  - name: PoolName
    type: string
    default: Default
  - name: TerraformVersion
    type: string
    default: 'latest'

jobs:
  - job: Install_Terraform
    displayName: ${{ if and(ne(parameters.ClientName, ''), ne(parameters.Environment, '')) }}Install Terraform - ${{ parameters.ClientName }} - ${{ parameters.Environment }}${{ else if ne(parameters.ClientName, '') }}Install Terraform - ${{ parameters.ClientName }}${{ else if ne(parameters.Environment, '') }}Install Terraform - ${{ parameters.Environment }}${{ else }}Install Terraform${{ end }}
    pool:
      name: ${{ parameters.PoolName }}
    steps:
      - checkout: none
      - task: TerraformInstaller@1
        displayName: "Install Terraform CLI (${{ parameters.TerraformVersion }})"
        inputs:
          terraformVersion: '${{ parameters.TerraformVersion }}'