parameters:
  - name: ClientName
    type: string
  - name: Environment
    type: string
  - name: PoolName
    type: string

jobs:
  - job: Terraform_Init
    displayName: "Terraform Init - ${{ parameters.ClientName }}-${{ parameters.Environment }}"
    pool:
      name: ${{ parameters.PoolName }}
    steps:
      - checkout: self
      - task: TerraformTask@5
        displayName: 'Terraform Init'
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: 'terraform/environments/${{ parameters.Environment }}'
          backendServiceArm: '$(TF_BACKEND_ARM)'
          backendAzureRmResourceGroupName: '$(TF_BACKEND_RG_NAME)'
          backendAzureRmStorageAccountName: '$(TF_STORAGE_ACCOUNT)'
          backendAzureRmContainerName: '$(TF_BACKEND_CONTAINER)'
          backendAzureRmKey: '${{ parameters.Environment }}/${{ parameters.ClientName }}.tfstate'
