apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.rediscache.password | b64enc | quote }}
