
parameters:
  - name: ClientName
    type: string
  - name: Environment
    type: string
  - name: pool
    type: object
    default:
      name: Default

jobs:
  - job: Terraform
    displayName: 'Terraform Infrastructure'
    pool: ${{ parameters.pool }}
    steps:
      - checkout: self
      - task: TerraformTaskV5@5
        displayName: 'Terraform Init'
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: 'terraform/environments/${{ parameters.Environment }}'
          backendServiceArm: '$(ARM_CONNECTION)'
          backendAzureRmResourceGroupName: '$(TF_BACKEND_RG_NAME)'
          backendAzureRmStorageAccountName: '$(TF_STORAGE_ACCOUNT)'
          backendAzureRmContainerName: '$(TF_BACKEND_CONTAINER)'
          backendAzureRmKey: '${{ parameters.Environment }}/${{ parameters.ClientName }}.tfstate'
      - task: TerraformTaskV5@5
        displayName: 'Terraform Plan'
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: 'terraform/environments/${{ parameters.Environment }}'
          environmentServiceNameAzureRM: '$(ARM_CONNECTION)'
          vars: |
            client_name=${{ parameters.ClientName }}
            environment=${{ parameters.Environment }}
      - task: TerraformTaskV5@5
        displayName: 'Terraform Apply'
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: 'terraform/environments/${{ parameters.Environment }}'
          environmentServiceNameAzureRM: '$(ARM_CONNECTION)'
          vars: |
            client_name=${{ parameters.ClientName }}
            environment=${{ parameters.Environment }}
          ensureBackend: true
          allowTelemetryCollection: true
