# Clean Terraform orchestrator
parameters:
  - name: ClientName
    type: string
  - name: Environment
    type: string
  - name: PoolName
    type: string
    default: Default

jobs:
  - template: ./terraform/install-terraform.yml
    parameters:
      ClientName: ${{ parameters.ClientName }}
      Environment: ${{ parameters.Environment }}
      PoolName: ${{ parameters.PoolName }}
      TerraformVersion: '1.13.3'

  - template: ./terraform/terraform-init.yml
    parameters:
      ClientName: ${{ parameters.ClientName }}
      Environment: ${{ parameters.Environment }}
      PoolName: ${{ parameters.PoolName }}

  - template: ./terraform/terraform-plan.yml
    parameters:
      ClientName: ${{ parameters.ClientName }}
      Environment: ${{ parameters.Environment }}
      PoolName: ${{ parameters.PoolName }}

  - template: ./terraform/terraform-apply.yml
    parameters:
      ClientName: ${{ parameters.ClientName }}
      Environment: ${{ parameters.Environment }}
      PoolName: ${{ parameters.PoolName }}
